### ISSUE TITLE
please guide me to how to open this project in Android Studio

### ISSUE THREAD

**Issue by ShankaMahakumbura** [sms2000/GPSToggler#4]
I am new to root android projects and widgets.
please help me to open this project in Android Studio.

Thank you in advance!

**Comment by sms2000** [comment]
Hi 

I used AS 2.2 (the last one) and git to download the project right now. AS 2.2 opened it out of the box.

What is a problem?

The root directory of the project is what you need to open. 

Google development site provides a lot of info for AS.

https://developer.android.com/training/index.html

Yours

Sergey

**Comment by ShankaMahakumbura** [comment]
ok i got the point and Thanks for that.
but i cant debug this project from AS. that's what i am telling bro.
also i used , find usages option in AS, but it did not gave me solution.
__
or simply please tell me, i want to plug this Gps Toggling mechanism to an existing app.
please give me advice.

**Comment by sms2000** [comment]
Hi

I’m not fluent with AS myself, always preferred Eclipse + Android SDK/NDK.

I know little about Graddle. 

But I know it’s pretty straightforward to debug.

If you can build and run the project (you have an APK) it’s sure debugable.

Set breakpoints in MainActivity and select in the menu “Run” -> “Debug”.

Regarding the code.

Check ‘actuators’ and how those called from TogglerService.

Check ‘su’ and the RootCaller to understand what need to be done for the APK having root and system level access.

You can see before Nougat it could be possible to  tear off the rest of the code and use actuators independently.

For Nougat the code is tightly coupled with all the root processing.

I’m sceptical it would be ease to separate. 

Yours

Sergey

**Comment by ShankaMahakumbura** [comment]
Hi
i want an advice/help from you for my research app.
i want to develope a root application to work on android phones to switch on 3g and gps automatically (without users interaction) and timely check weather gps and 3g is off or not and switch them on again if off.
please let me know how to achieve it.

**Comment by sms2000** [comment]
Hi

Unfortunately I have no time for full scale tutoring. 

The code provided AS IS for free and can be used as a model or reference for experienced Android developers.

3G toggling on and off is not a topic of this code at all.

Best wishes

Sergey

**Comment by ShankaMahakumbura** [comment]
thank you for the reply :)
